general {
    ignore_empty_input = true
}

background {
    monitor =
    color = rgb(1a1a1a)
    blur_passes = 3
}

animations {
    enabled = false
}

input-field {
    monitor =
    size = 650, 100
    position = 0, 0
    halign = center
    valign = center

    inner_color = rgb(2a2a2a)
    outer_color = rgba(33ccffee)
    outline_thickness = 4

    font_family = JetBrainsMono Nerd Font
    font_color = rgb(ffffff)

    placeholder_text = Enter Password
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 0
    shadow_passes = 0
    fade_on_empty = false
}
