# my hyprland

$terminal = ghostty
$fileManager = nautilus
$browser = zen-browser
$editor = nvim

source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/monitors.conf

windowrule = noscreenshare, class:^(1[p|P]assword)$
windowrule = tag +floating-window, class:^(1[p|P]assword)$
